### ISSUE TITLE
Class method defaultLayout

### ISSUE THREAD

**Issue by LNUitTutor** [SquareBracketAssociates/CodeOfSpec20Book#2]
There are two methods _defaultLayout_ in the package CodeOfSpec20Book: 
- an instance method _CustomerSatisfactionPresenter >> defaultLayout_ and
- a class method _CustomerSatisfactionPresenter class>> defaultLayout_

Are both methods necessary? Only the first one is mentioned in the booklet.

**Comment by demarey** [comment]
Hi, 
Only the instance method should be necessary.

**Comment by LNUitTutor** [comment]
Super! The class method should be removed from the repository.

**Comment by koendehondt** [comment]
The class-level method was removed a while ago so I will close this ticket.

**Comment by Ducasse** [comment]
Tx
