### ISSUE TITLE
Metacello fails to load it

### ISSUE THREAD

**Issue by LazyOtto** [SquareBracketAssociates/CodeOfSpec20Book#6]
Pharo 12.0 on MacOS 14.7

After evaluating (pure copy/paste from the .md):
> Metacello new
>     baseline: 'CodeOfSpec20Book';
>     repository: 'github://SquareBracketAssociates/CodeOfSpec20Book/src';
>     load

After a long delay:
"failed to connect to github.com: Operation timed out"

Looks like some network traffic is going on before that happens. 

Something changed/wrong with the structure of the directories/files/packaging?

**Comment by Ducasse** [comment]
Thanks
This is super strange because I can browse with safari
https://github.com/SquareBracketAssociates/CodeOfSpec20Book/

but I get an 404 on 
https://github.com/SquareBracketAssociates/CodeOfSpec20Book/src

and there is an src folder there.

So this is probably correct and GH is hidding the structure as shown below.

**Comment by Ducasse** [comment]
Now browsing 

https://github.com/SquareBracketAssociates/CodeOfSpec20Book/tree/master/src

is working

**Comment by Ducasse** [comment]
I will ask around

**Comment by Ducasse** [comment]
Now I tool Pharo 12
pasted your code in a playground and do it and it loads.

```
Metacello new
baseline: 'CodeOfSpec20Book';
repository: 'github://SquareBracketAssociates/CodeOfSpec20Book/src';
load
```

So can you retry.

**Comment by koendehondt** [comment]
The URL was wrong. It should have been:

```smalltalk
Metacello new
    baseline: 'CodeOfSpec20Book';
    repository: 'github://SquareBracketAssociates/CodeOfSpec20Book:master/src';
    load
```

I [fixed the URL](https://github.com/SquareBracketAssociates/CodeOfSpec20Book/commit/a802cb48c9e8afbfa12293d198df7d391791925f) in the readme.

**Comment by koendehondt** [comment]
@LazyOtto Thank you for reporting the bug.
Note that we are in the process of finalizing the book. The code examples are updated regularly to reflect the latest changes in the book.

**Comment by Ducasse** [comment]
Tx I was too sleepy :)

**Comment by LazyOtto** [comment]
Thank you both for super quick response. However, please read below about the root cause problem I found.

It was still failing. I saw that it was attempting, and failing, to connect via Port 22 / SCP.

Please note that a clean/default Pharo 12.0 image has this configuration in Settings:
￼

After changing to use this:
HTTPS (https://github.com/<username>/<project>.git)

I had success with:
--
Metacello new
    baseline: 'CodeOfSpec20Book';
    repository: 'github://SquareBracketAssociates/CodeOfSpec20Book:master/src';
    load
—

Therefore, this probably surfaced an issue not with this specific github repository, but with needing either different defaults set in the image or some comments in every repositories' README.md about needing to configure Iceberg/Metacello integration before evaluating the snippet provided for copy/paste/doit.

**Comment by koendehondt** [comment]
@LazyOtto Please submit an [issue to the Pharo project](https://github.com/pharo-project/pharo/issues), as this problem is not related to the code ohe the Spec book.
